version: '3.8'
services:
  common:
    build:
      context: .
      dockerfile: common/Dockerfile
      args:
        BUILD_VERSION: $BUILD_VERSION
    image: common:$BUILD_VERSION
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: $BUILD_VERSION
        BUILD_CONTEXT: api
    image: api:$BUILD_VERSION
    depends_on:
      - common
    ports:
      - 3000:3000
  background-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: $BUILD_VERSION
        BUILD_CONTEXT: background-worker
    image: background-worker:$BUILD_VERSION
    depends_on:
      - common
    environment:
      CRON_JOB_SCHEDULE: "0 * * * *"
    ports:
      - 3002:3002